apiVersion: v2
name: cert-status-exporter
description: Monitors and exposes PKI information as Prometheus metrics including expiriation time of certificates in secrets and the status of the parent Certificate object

type: application
version: v1.0.4
appVersion: v1.0.4

# 1.0.2 - Add default prometheus rules
